### ISSUE TITLE
デフォルトの都市の選択を東京に変更してください

### ISSUE THREAD

**Issue by iwagon-gm** [iwagon-networks/meeting-time#16]
@iwagon-networks/dev 

本サービスの利用者は日本からのアクセスが多いため、変更を希望します。
よろしくお願いします。　:bow:

**Comment by iwagon12** [comment]
ごしてきご最もです。
修正します。

@iwagonp 修正してください

**Comment by iwagonp** [comment]
了解しました。修正します。

**Comment by iwagon** [comment]
Close
